services:
  database:
    image: postgres:16.1
    container_name: data-mart-db
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB = data-mart-db
      - POSTGRES_USER = user
      - POSTGRES_PASSWORD = 12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10