CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login varchar NOT NULL,
    name varchar NOT NULL,
    password varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS connections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host varchar NOT NULL,
    port BIGINT NO NULL,
    db_name varchar,
    db_user varchar,
    db_password varchar,
    display_name varchar,
    user_id BIGINT,
    created TIMESTAMP NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS datasets (
    id BIGINT,
    user_id BIGINT,
    connection_id BIGINT,
    scheme varchar,
    table_name varchar NOT NULL,
    created TIMESTAMP NOT NULL,
    PRIMARY KEY id,
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    FOREIGN KEY (connection_id) REFERENCES connections(connection_id)

);

CREATE TABLE IF NOT EXISTS views (
    id BIGINT,
    user_id BIGINT,
    created TIMESTAMP NOT NULL,
    PRIMARY KEY id,
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS sql_queries (
    id BIGINT,
    query varchar NOT NULL,
    user_id BIGINT,
    created TIMESTAMP NOT NULL,
    PRIMARY KEY id,
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);