--drop table datasets, sql_queries, views, connections, users;

--drop table users_roles, roles, datasets, sql_queries, views, connections, users;

CREATE TABLE IF NOT EXISTS roles (
    role_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstname VARCHAR NOT NULL,
    lastname VARCHAR NOT NULL,
    username VARCHAR UNIQUE NOT NULL,
    password VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS users_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users (user_id),
    role_id INTEGER REFERENCES roles (role_id)
);

CREATE TABLE IF NOT EXISTS connections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host VARCHAR NOT NULL,
    port BIGINT NOT NULL,
    db_name VARCHAR NOT NULL,
    db_user VARCHAR NOT NULL,
    db_password VARCHAR NOT NULL,
    display_name VARCHAR NOT NULL,
    db_type VARCHAR,
    user_id BIGINT,
    created TIMESTAMP NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS datasets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    connection_id BIGINT,
    scheme VARCHAR,
    table_name VARCHAR NOT NULL,
    created TIMESTAMP NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    FOREIGN KEY (connection_id) REFERENCES connections(id)
);

CREATE TABLE IF NOT EXISTS chart (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR NOT NULL,
    table_name VARCHAR NOT NULL,
    chart_type VARCHAR NOT NULL,
    row_limit INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS table_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chart_id BIGINT,
    header VARCHAR NOT NULL,
    data VARCHAR NOT NULL,
    FOREIGN KEY (chart_id) REFERENCES chart(id)
);

CREATE TABLE IF NOT EXISTS line_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chart_id BIGINT,
    x_data VARCHAR NOT NULL,
    y_data VARCHAR NOT NULL,
    FOREIGN KEY (chart_id) REFERENCES chart(id)
);

CREATE TABLE IF NOT EXISTS sql_queries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query VARCHAR NOT NULL,
    user_id BIGINT,
    created TIMESTAMP NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);